apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    kubernetes.io/name: heapster-influxdb
  name: heapster-influxdb
  namespace: kube-system
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    k8s-app: influxdb
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: heapster-influxdb
  namespace: kube-system
  annotations:
    volume.beta.kubernetes.io/storage-class: "kismatic"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster-influxdb
  namespace: kube-system
  annotations:
    kismatic/version: "{{ kismatic_short_version }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      containers:
      - name: influxdb
        image: "{{ influxdb_img }}"
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        persistentVolumeClaim:
          claimName: heapster-influxdb
